### ISSUE TITLE
Bugs related to sylius 1.9 latest version of sylius

### ISSUE THREAD

**Issue by aa-ahmed-aa** [odiseoteam/SyliusVendorPlugin#17]
Will list some issues i encounter with the bundle on the new version of sylius
## Versions
| #####  | Version |
| ------------- | ------------- |
| PHP  | 7.4.16  |
| Symfony  | 4.4.20  |
| Sylius  | 1.9.0  |
| Bundle  | 1.3  |

# 1 strict option is not existed 
#### Problem
![image](https://user-images.githubusercontent.com/9592546/111235497-7028b900-85f9-11eb-99fe-c364d6456c61.png)
#### Solution
when i tried to edit these two files 
1. `src/Resources/config/validation/VendorEmail.yaml`
2. `src/Resources/config/validation/Vendor.yaml`
and remove the ~~`strict: true`~~ it worked fine

# 2 Template References
#### Problem
![image](https://user-images.githubusercontent.com/9592546/111237957-c9dfb200-85fe-11eb-9c4a-be6a39630ec1.png)

#### Solution
here  `src/Resources/config/routing/admin/vendor.yaml`, i replaced this section `templates: SyliusAdminBundle:Crud` with `templates: '@SyliusAdmin\\Crud'`

**Comment by bigboss86** [comment]
New version has been released with this fixes! Thanks @aa-ahmed-aa
