### ISSUE TITLE
Adding features to the plugin

### ISSUE THREAD

**Issue by aimeric** [odiseoteam/SyliusVendorPlugin#2]
Hi @odiseoteam, 

I'm sure a lot of developers using Sylius will be interested with your multi vendor plugin,  but I think some important features should be added , here few suggestions:

- [ ]  A vendor should only be able to see ( edit, delete ) his own products.

- [ ]  In the dashboard tab the vendor should only see his orders and his total sales.

- [ ]  The tab configuration and client shouldn't be visible to a vendor, only to the admin of the website.

- [ ]  In the tab sales the vendor should only see his orders

- [ ]  When the admin user create a new vendor he should be able to create a password for the new vendor.

Aimeric :)

**Comment by bigboss86** [comment]
Hi @aimeric. You can view this features in our new Sylius Marketplace Plugin.
https://odiseo.io/plugins-and-bundles/premium/sylius-mvm-plugin
