### ISSUE TITLE
Cannot declare class ProductRepository, because the name is already in use.

### ISSUE THREAD

**Issue by GServices228** [odiseoteam/SyliusVendorPlugin#31]
Hello,Hope everything is well.
I'm following [the guide](https://github.com/odiseoteam/SyliusVendorPlugin/blob/master/doc/installation.md) to install the plugin but i'm getting this `error  Symfony\Component\ErrorHandler\Error\FatalError^ {#7876
  #message: "Compile Error: Cannot declare class ProductRepository, because the name is already in use"
  #code: 0
  #file: "./src/Repository/ProductRepository.php"
  #line: 9
  -error: array:4 [
    "type" => 64
    "message" => "Cannot declare class ProductRepository, because the name is already in use"
    "file" => "/www/wwwroot/app.germinalservices.com/goteach/src/Repository/ProductRepository.php"
    "line" => 9
  ]
} `  every time.when trying php bin/console doctrine:migrations:migrate.

Actions i took:
-Modify the class name in "src/Repository/ProductRepository.php" and config/packages/_sylius.yaml
-restarted from top but it still blocking there.

Any help will be appreciated.Thanks in advance

**Comment by bigboss86** [comment]
Hi @GServices228. Can you share the ProductRepository file?

**Comment by GServices228** [comment]
Hello,thanks for the prompt reply.
Here is the content:
`<?php
// src/Repository/ProductRepository.php

// ...
use Odiseo\SyliusVendorPlugin\Repository\ProductRepositoryInterface;
use Odiseo\SyliusVendorPlugin\Repository\ProductRepositoryTrait;
use Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductRepository as BaseProductRepository;

class ProductRepository extends BaseProductRepository implements ProductRepositoryInterface
{
    use ProductRepositoryTrait;

    // ...
}`

**Comment by bigboss86** [comment]
You forgot to add the namespace of this file

**Comment by bigboss86** [comment]
Should be "App\Repository"

```
<?php

declare(strict_types=1);

namespace App\Repository;

use Odiseo\SyliusVendorPlugin\Repository\ProductRepositoryInterface;
use Odiseo\SyliusVendorPlugin\Repository\ProductRepositoryTrait;
use Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductRepository as BaseProductRepository;

class ProductRepository extends BaseProductRepository implements ProductRepositoryInterface
{
    use ProductRepositoryTrait;
}
```
