### ISSUE TITLE
Can't update database

### ISSUE THREAD

**Issue by ghost** [odiseoteam/SyliusVendorPlugin#4]
while updating the database

`php bin/console doctrine:schema:update`

I get this error 

> The table with name 'app_dev.sylius_product_channels' already exists.

**Comment by odiseoteam** [comment]
Hi @karpdamian ! Did you tried drop the database before execute the update command?
We look forward.

**Comment by atamaniuc** [comment]
HI @odiseoteam  ! I've generated a new migration `doctrine:migrations:diff` and trying to migrate it `doctrine:migrations:migrate`. I have following error: `QLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'FK_F9EF269B72F5A1AA'; check that column/key exists`
