### ISSUE TITLE
Database migration issue

### ISSUE THREAD

**Issue by sachittandukar** [odiseoteam/SyliusVendorPlugin#5]
Whenever I try to migrate the database, following issue shows up.
```
ALTER TABLE sylius_channel_currencies DROP FOREIGN KEY FK_AE491F9372F5A1AA
Migration 20180213033415 failed during Execution. Error An exception occurred while executing 'ALTER TABLE sylius_channel_currencies DROP FOREIGN KEY FK_AE491F9372F5A1AA':
```

**Comment by sachittandukar** [comment]
Is this plugin still maintained?

**Comment by odiseoteam** [comment]
Hi @sachittandukar , sorry for the delay. 

We tried to reproduce the error but couldn't. Do you want to install the plugin in production enviroment?
Can you share us the project?

**Comment by sachittandukar** [comment]
Actually, I am working in dev environment and issue shows up when you generate migration files 
`php bin/console doctrine:migrations:diff`
and trying to migrate using the following command:
`php bin/console doctrine:migrations:migrate`

The only workaround is to force schema update. Otherwise, I keep getting above mentioned error message.

**Comment by odiseoteam** [comment]
hi @sachittandukar. Can you try to reproduce the error again? We released a new version.
