### ISSUE TITLE
Wrong image path

### ISSUE THREAD

**Issue by KriBetko** [odiseoteam/SyliusVendorPlugin#7]
Have trouble with image path

|| URL |
| ------------- | ------------- |
| Expected  | /media/vendor-logo/myvendor.png  |
| Got  | /media/cache/resolve/odiseo_sylius_vendor_logo/myvendor.png  |

Sylius: ^1.2
sylius-vendor-plugin: ^1.0

**Comment by odiseoteam** [comment]
Hi @KriBetko, 

The image path stored in the db has only the image filename. In the frontend that filename is passed to a twig filter named imagine_filter that returns a image path you got. That twig filter is from the Liip ImagineBundle https://github.com/liip/LiipImagineBundle.

So, the image path you got is ok.

Let me know if it was clear for you.

**Comment by KriBetko** [comment]
Filter 'odiseo sylius vendor_logo' returns wrong path. Folder "%kernel.root_dir%/../web/media/cache/resolve/odiseo_sylius_vendor_logo" doesn't exist. Is problem with SyliusVendorPlugin or LiipImagineBundle?

**Comment by odiseoteam** [comment]
@KriBetko please create the /web/media/image folder manually and try again

**Comment by KriBetko** [comment]
It's works. Thanks
