### ISSUE TITLE
Update plugin to support Sylius 1.4

### ISSUE THREAD

**Issue by psihius** [odiseoteam/SyliusVendorPlugin#9]
Sylius 1.4 has been released and it seems the plugin could just bump it's version without changes so we can update our stores :)

**Comment by songecko** [comment]
Hi @psihius . We will do it soon, feel free to make a PR if you want.

**Comment by b7582** [comment]
Hi @songecko , 
Have you planned a date for this upgrade version release ?
Thank you very much.

**Comment by songecko** [comment]
It's done!
